Added static typing information to LiSA
UniVE-SSV/lisa pull request #10
Opened 2020-10-26 16:40 UTC by VincenzoArceri

**Description**
Added static typing information to LiSA, following the suggested implementation reported in #9.  
- The type interface ```Type``` has been added, extended by the type sub-interfaces ```NumericType```, ```BooleanType``` and ```StringType```;
- No concrete type has been introduced except for the type ```Untyped```, implemented as a singleton. Any concrete type that will be defined in the future should be implemented following the singleton design pattern;
- The static type information has been added to ```Expression``` as a protected field: when the type is not provided, ```Untyped``` type is used as default;
- The return type of ```CFG``` is captured by its descriptor, namely ```CFGDescriptor```, with the protected field ```returnType```: as above, if no return type is provided for the descriptor, ```Untyped```type is used as default.
- In ```CFGDescriptor```, the type of the arguments names (```argNames```) was changed from array of strings (```String[]```) to array of variables (```Variable[]```). In this way, it possible to capture the arguments names together with their types (since ```Variable```has static type information being an expression).
- Also ```Literal```, being an expression, has static type information. LiSA has only the concrete literal ```NullLiteral```and for the moment it has no type information (namely, the type of ```NullLiteral``` is  ```Untyped```). Should be implement the LiSA internal type ```NullType```?

**Implemented features**
Closes #9

2020-10-27 08:48 UTC, lucaneg requested changes
In general, Javadoc on types should be improved.

2020-10-27 08:48 UTC, lucaneg commented on lisa/src/main/java/it/unive/lisa/cfg/CFGDescriptor.java
> +	private final Variable[] argNames;
These should be called arguments since we are no longer tracking just their names

2020-10-27 08:48 UTC, lucaneg commented on lisa/src/main/java/it/unive/lisa/cfg/CFGDescriptor.java
> +	public Variable[] getArgNames() {
This should change accordingly since we will be changing also the field name.

2020-10-27 08:48 UTC, lucaneg commented on lisa/src/main/java/it/unive/lisa/cfg/statement/Expression.java
> +	protected final Type type;
It should be explicit that this is the **static** type of the expression

2020-10-27 08:48 UTC, lucaneg commented on lisa/src/main/java/it/unive/lisa/cfg/statement/Expression.java
> +	public Type getType() {
Rename this method as **getStaticType**.

2020-10-27 08:48 UTC, lucaneg commented on lisa/src/main/java/it/unive/lisa/cfg/type/Untyped.java
> +public enum Untyped implements Type {
I think it's better if we turn this into a regular class with a private constructor and a **public static final** singleton field.

2020-10-27 08:48 UTC, lucaneg commented on lisa/src/main/java/it/unive/lisa/cfg/statement/Literal.java
>  	public Literal(CFG cfg, Object value) {
There should also be a constructor with cfg, value and type (as it happens with Variable)

2020-10-27 08:48 UTC, lucaneg commented on lisa/src/main/java/it/unive/lisa/cfg/type/Type.java
> + * Type interface.
We should make it explicit (probably here) that instances of this interface should be unique to help implementers.

2020-10-27 10:42 UTC, lucaneg approved these changes

2020-10-27 16:24 UTC, lucaneg approved these changes

2020-10-27 16:24 UTC, merged

2020-10-29 11:50 UTC, VincenzoArceri commented
Need to re-open this pull request since static typing information about Call (native, open and CFG call) was missing.